# Generated by Django 4.2.15 on 2025-02-21 16:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dosage', models.CharField(help_text='e.g., 1 tablet, 5 ml', max_length=100)),
                ('frequency', models.CharField(help_text='e.g., twice a day, once a day', max_length=100)),
                ('duration', models.CharField(help_text='e.g., 7 days, 2 weeks', max_length=100)),
                ('when_to_eat', models.CharField(choices=[('before_meal', 'Before Meal'), ('after_meal', 'After Meal'), ('with_meal', 'With Meal'), ('empty_stomach', 'Empty Stomach'), ('anytime', 'Anytime')], help_text='When to take the medication', max_length=50)),
                ('with_liquid', models.CharField(choices=[('normal_water', 'Normal Water'), ('lukewarm_water', 'Lukewarm Water'), ('milk', 'Milk'), ('sweet_milk', 'Sweet Milk'), ('juice', 'Juice'), ('no_liquid', 'No Liquid')], help_text='What to take the medication with', max_length=50)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pharmacyproduct')),
            ],
        ),
    ]
