# Generated by Django 4.2.15 on 2025-02-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('doctor', '0002_initial'),
        ('user', '0001_initial'),
        ('medications', '0001_initial'),
        ('patient', '0001_initial'),
        ('diagnostics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiondetail',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_details', to='user.organization'),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='medications.prescription'),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_details', to='sites.site'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='diagnostics.diagnosis'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='user.organization'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='sites.site'),
        ),
    ]
