# Generated by Django 4.2.15 on 2025-02-21 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=550)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
                ('fee', models.PositiveIntegerField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Canceled', 'Canceled'), ('Done', 'Done')], max_length=15)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventMessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_sent_48', models.BooleanField(default=False)),
                ('is_sent_24', models.BooleanField(default=False)),
                ('is_sent_1', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
