# Generated by Django 4.2.15 on 2025-04-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='bill_to',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='status',
        ),
    ]
