# Generated by Django 4.2.15 on 2025-04-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received')], default='received', max_length=50),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('UPI', 'Upi')], default='cash'),
        ),
    ]
