# Generated by Django 4.2.15 on 2025-05-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_purchaseorder_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyproduct',
            name='sku',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('gel', 'Gel'), ('oil', 'Oil'), ('ointment', 'Ointment'), ('cream', 'Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('spray', 'Spray'), ('suppository', 'Suppository'), ('patch', 'Patch'), ('powder', 'Powder'), ('granules', 'Granules'), ('lozenge', 'Lozenge'), ('paste', 'Paste'), ('shampoo', 'Shampoo'), ('solution', 'Solution'), ('suspension', 'Suspension'), ('emulsion', 'Emulsion'), ('transdermal_patch', 'Transdermal Patch'), ('oral_strip', 'Oral Strip')], default='tablet', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='sku',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('gel', 'Gel'), ('oil', 'Oil'), ('ointment', 'Ointment'), ('cream', 'Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('spray', 'Spray'), ('suppository', 'Suppository'), ('patch', 'Patch'), ('powder', 'Powder'), ('granules', 'Granules'), ('lozenge', 'Lozenge'), ('paste', 'Paste'), ('shampoo', 'Shampoo'), ('solution', 'Solution'), ('suspension', 'Suspension'), ('emulsion', 'Emulsion'), ('transdermal_patch', 'Transdermal Patch'), ('oral_strip', 'Oral Strip')], default=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('gel', 'Gel'), ('oil', 'Oil'), ('ointment', 'Ointment'), ('cream', 'Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('spray', 'Spray'), ('suppository', 'Suppository'), ('patch', 'Patch'), ('powder', 'Powder'), ('granules', 'Granules'), ('lozenge', 'Lozenge'), ('paste', 'Paste'), ('shampoo', 'Shampoo'), ('solution', 'Solution'), ('suspension', 'Suspension'), ('emulsion', 'Emulsion'), ('transdermal_patch', 'Transdermal Patch'), ('oral_strip', 'Oral Strip')], max_length=100, null=True),
        ),
    ]
