# Generated by Django 4.2.15 on 2025-04-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='creates_at',
            new_name='created_at',
        ),
    ]
