# Generated by Django 4.2.15 on 2025-04-03 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('user', '0003_rename_creates_at_attendance_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ips', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='org_white_ips', to='sites.site')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='site_white_ips', to='sites.site')),
            ],
        ),
    ]
