# Generated by Django 4.2.15 on 2025-04-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('user', '0005_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='created_at',
            new_name='in_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='organisation',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='user.organization'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, related_name='attendances', to='sites.site'),
        ),
    ]
