# Generated by Django 4.2.15 on 2025-04-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_created_at_attendance_in_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-in_time']},
        ),
    ]
