# Generated by Django 4.2.15 on 2025-04-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_appointment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='token_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
